### PR TITLE
[improve] make app debuggable

### PR DESCRIPTION
**Pull request by ValkoVolodya**
#4 
So, this pull request introduce correct work with dev server without performing _react-scripts eject_ via this [article](https://medium.freecodecamp.org/building-an-electron-application-with-create-react-app-97945861647c)
tltr: to start live development session simply run _npm run dev_

### CODE REVIEW

**Comment by anxolerd** [comment]
Can you please:

1. Run the development build with `npm start` command
2. Make webpack dev server to not open browser window

?

**Comment by anxolerd** [comment]
For the item 2 please see: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-dev-utils/openBrowser.js#L115

**Comment by ValkoVolodya** [comment]
So, I think recent problem with foreman that kills process reproduces only on Mac.
Please, try to run project in dev mode after this change, if it all OK, my assumption is true.

**Comment by anxolerd** [comment]
Cannot reproduce the described issue on Linux.
I've fixed a few issues like missing script and devtools being open by default.

**Pull request merged**
