### PR TITLE
Introduce webpack

### PR DESCRIPTION
**Pull request by ValkoVolodya**
This pull request should help to solve issue #4

### CODE REVIEW

**Comment by ValkoVolodya** [comment]
With introducing eslint there are issues, that lint finds, I can fix it, if needed

**Comment by ValkoVolodya** [comment]
This is article that describes webServer configuration, but without ejecting app
https://medium.freecodecamp.org/building-an-electron-application-with-create-react-app-97945861647c

**Comment by anxolerd** [comment]
@ValkoVolodya so you suggest we can have nice debuggable build without ejecting an app? If so that would be great, because the config files ejected from react-scripts are complicated in my opinion.

**Comment by ValkoVolodya** [comment]
Based on article, we can, so I`ll try it soon

**Comment by ValkoVolodya** [comment]
Decided to proceed without performing eject, so I close this PR

**Pull request closed without merging**
